# Generated by Django 5.1 on 2024-11-03 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0016_alter_userprofile_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='estudiantes',
            field=models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='asignaciones_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios_api.materias'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='profesor',
            field=models.ForeignKey(default=1, limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100),
        ),
    ]
