# Generated by Django 5.1 on 2024-11-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0017_remove_asignacion_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
