# Generated by Django 5.1 on 2024-11-19 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0018_asignacion_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='archivo',
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='uploads/')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='usuarios_api.asignacion')),
            ],
        ),
    ]
