# Generated by Django 5.1 on 2024-11-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0019_remove_asignacion_archivo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
