# Generated by Django 5.1 on 2024-11-24 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0021_entrega_respuestaasig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestaasig',
            old_name='fechaEnvio',
            new_name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='respuestaasig',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='respuestas/'),
        ),
        migrations.AlterField(
            model_name='respuestaasig',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
