# Generated by Django 5.1 on 2024-11-24 21:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0022_rename_fechaenvio_respuestaasig_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestaasig',
            old_name='fecha_entrega',
            new_name='fechaEnvio',
        ),
        migrations.RemoveField(
            model_name='respuestaasig',
            name='archivo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='respuestaasig',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.estudiante'),
        ),
    ]
