# Generated by Django 5.1 on 2024-11-28 00:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0025_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.RegexValidator(message='La calificación debe ser un número entre 0 y 100 con hasta 2 decimales.', regex='^\\d+(\\.\\d{1,2})?$')])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuarios_api.asignacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuarios_api.estudiante')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'unique_together': {('estudiante', 'asignacion')},
            },
        ),
    ]
