# Generated by Django 5.1 on 2024-11-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0027_nota_entrega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={},
        ),
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
