# Generated by Django 5.1 on 2024-11-28 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0028_alter_nota_options_alter_nota_calificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.RemoveField(
            model_name='nota',
            name='entrega',
        ),
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.RegexValidator(message='La calificación debe ser un número entre 0 y 100 con hasta 2 decimales.', regex='^\\d+(\\.\\d{1,2})?$')]),
        ),
    ]
