# Generated by Django 5.1 on 2024-11-29 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0029_alter_nota_options_remove_nota_entrega_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nota',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuarios_api.entrega'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'asignacion', 'entrega')},
        ),
    ]
