# Generated by Django 5.1 on 2024-11-29 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0030_alter_nota_unique_together_nota_entrega_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'asignacion')},
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='nota',
            name='entrega',
        ),
    ]
