# Generated by Django 5.1 on 2024-11-30 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0032_alter_nota_calificacion_alter_nota_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.estudiante'),
        ),
    ]
