# Generated by Django 5.1 on 2024-11-30 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0033_alter_entrega_estudiante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nota',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.asignacion'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.estudiante'),
        ),
        migrations.RemoveField(
            model_name='nota',
            name='fecha_asignacion',
        ),
    ]
