# Generated by Django 5.1 on 2024-11-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0035_nota_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
