# Generated by Django 5.1 on 2024-12-01 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0036_nota_fecha_asignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='calificacion',
        ),
    ]
