# Generated by Django 5.1 on 2024-12-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0037_remove_nota_asignacion_remove_nota_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
