# Generated by Django 5.1 on 2024-12-01 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0038_nota_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuarios_api.asignacion'),
        ),
    ]
