# Generated by Django 5.1 on 2024-12-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0039_nota_asignacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nota',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='usuarios_api.nota'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(blank=True, to='usuarios_api.materias'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuarios_api.estudiante'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to='usuarios_api.estudiante'),
        ),
    ]
