# Generated by Django 5.1 on 2024-12-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0040_rename_user_estudiante_user_profile_estudiante_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
