# Generated by Django 5.1 on 2024-12-01 03:40

import usuarios_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0042_alter_entrega_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name=usuarios_api.models.UserProfile),
        ),
    ]
