# Generated by Django 5.1 on 2024-12-04 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0043_alter_estudiante_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='estudianteid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
