# Generated by Django 5.1 on 2024-12-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0044_nota_estudianteid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='estudianteid',
        ),
    ]
