# Generated by Django 5.1 on 2024-12-05 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0045_remove_nota_estudianteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota', to=settings.AUTH_USER_MODEL),
        ),
    ]
