# Generated by Django 5.1 on 2024-12-05 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0046_nota_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL),
        ),
    ]
