# Generated by Django 5.1 on 2024-12-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0048_alter_nota_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='estudiante',
        ),
    ]
