# Generated by Django 5.1 on 2024-12-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0049_remove_nota_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_by',
        ),
    ]
